const { test } = require('node:test');
const assert = require('node:assert/strict');
const { newDb, DataType } = require('pg-mem');
const memory = newDb();
const textArray = memory.public.getType(DataType.text).asArray();
memory.public.registerFunction({name:'array_append',args:[textArray,DataType.text],returns:textArray,implementation:(array,item)=>[...array,item]});
const { Pool } = memory.adapters.createPg();
const pool = new Pool();
const db = require('../src/db/postgres');
db.query = (...args) => pool.query(...args);
db.getPool = () => pool;
const service = require('../src/services/collaborationService');
require('../src/services/emailService').configured = () => false;
require('../src/services/emailService').sendEmail = async () => ({sent:false,reason:'Prueba sin correo externo.'});
const express = require('express');
const app = express();app.use(express.json());
const localRepository = require('../src/repositories/dbRepository');
localRepository.readDb = async () => ({tasks:[{id:'private-task',userId:owner.id,title:'Privada',dueAt:'2026-10-08T18:00:00Z',completed:false}]});
localRepository.writeDb = async () => {throw new Error('No se esperaba escritura de una tarea ajena.');};
app.use('/api/tasks',require('../src/routes/taskRoutes'));
app.use('/api/collaboration',require('../src/routes/collaborationRoutes'));
app.use(require('../src/middleware/errorHandler').errorHandler);
const owner = {id:'00000000-0000-4000-8000-000000000001',name:'Ana',email:'ana@example.com'};
const member = {id:'00000000-0000-4000-8000-000000000002',name:'Luis',email:'luis@example.com'};

test('invitation permissions, acceptance, revocation and conflicting saves', async t => {
  await pool.query('CREATE TABLE naatzo_users(id UUID PRIMARY KEY,name TEXT,email TEXT)');
  for(const user of [owner,member])await pool.query('INSERT INTO naatzo_users VALUES($1,$2,$3)',[user.id,user.name,user.email]);
  const tokens={owner:await service.createSession(owner.id),member:await service.createSession(member.id)};
  const server=app.listen(0);await new Promise(resolve=>server.once('listening',resolve));
  t.after(()=>{server.close();pool.end();});
  const base=`http://127.0.0.1:${server.address().port}/api/collaboration`;
  async function request(path,role='owner',method='GET',body) {
    const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(role?{Authorization:`Bearer ${tokens[role]}`}:{})},body:body?JSON.stringify(body):undefined});
    return {status:response.status,data:response.status===204?null:await response.json()};
  }
  assert.equal((await request('/status',null)).status,401);
  tokens.jwt=require('../src/modules/team/middleware/auth').signToken(owner);
  assert.equal((await request('/status','jwt')).status,200);
  const payload={id:'00000000-0000-4000-8000-000000000003',title:'Equipo',members:[],tasks:[],document:{name:'minuta.txt',data:'data:text/plain;base64,'+Buffer.from('Descripción del equipo y sus tareas.').toString('base64')}};
  const created=await request('/projects','owner','POST',payload);
  assert.equal(created.status,201);
  const project=created.data.project;
  assert.deepEqual(project.document,payload.document);
  const retried=await request('/projects','owner','POST',payload);
  assert.equal(retried.status,200);
  assert.equal(retried.data.project.id,project.id);
  assert.equal((await request('/projects','member','POST',payload)).status,404);
  assert.equal((await request('/projects','owner','POST',{...payload,id:undefined,document:{name:'x.exe',data:payload.document.data}})).status,400);
  assert.equal((await request(`/projects/${project.id}`,'member')).status,404);
  const invitation=await request(`/projects/${project.id}/invitations`,'owner','POST',{email:member.email});
  assert.equal(invitation.status,201);assert.equal(invitation.data.delivery.sent,false);
  const token=new URL(invitation.data.url).pathname.split('/').pop();
  assert.equal((await request(`/invitations/${token}`,null)).status,200);
  assert.equal((await request(`/invitations/${token}/accept`,'owner','POST')).status,403);
  const accepted=await request(`/invitations/${token}/accept`,'member','POST');
  assert.equal(accepted.status,200,JSON.stringify(accepted.data));assert.equal(accepted.data.project.members.filter(m=>m.userId===member.id).length,1);
  assert.equal((await request(`/invitations/${token}/accept`,'member','POST')).data.project.members.length,2);
  assert.equal((await request(`/projects/${project.id}/invitations`,'member','POST',{})).status,404);
  assert.equal((await request(`/projects/${project.id}`,'owner','PATCH',project)).status,409);
  assert.equal((await request(`/projects/${project.id}`,'member','PATCH',accepted.data.project)).status,200);
  assert.equal((await request(`/projects/${project.id}/invitations/${invitation.data.id}`,'owner','DELETE')).status,204);
  assert.equal((await request(`/invitations/${token}`,null)).status,410);
  const taskBase = base.replace('/collaboration','/tasks');
  const list = await fetch(taskBase+`?userId=${owner.id}`,{headers:{Authorization:`Bearer ${tokens.member}`}});
  assert.deepEqual((await list.json()).tasks,[]);
  const update = await fetch(taskBase+'/private-task',{method:'PATCH',headers:{Authorization:`Bearer ${tokens.member}`,'Content-Type':'application/json'},body:JSON.stringify({completed:true})});
  assert.equal(update.status,404);
  assert.equal((await fetch(taskBase)).status,401);
});
