-- Naatzo: ejecutar en SQL Editor de un proyecto NUEVO de Supabase.
-- Solo agrega el usuario test@test.com / 12345. No borra datos existentes.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- Hacka2026 tutor database example for Supabase/Postgres.
-- Run this in Supabase SQL Editor.

CREATE EXTENSION IF NOT EXISTS vector;

-- Public learning resources: PDFs, public pages, digital libraries, etc.
CREATE TABLE IF NOT EXISTS public.resources (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT,
  source_name TEXT,
  resource_type TEXT NOT NULL DEFAULT 'web',
  subject TEXT,
  grade_level TEXT,
  language TEXT NOT NULL DEFAULT 'es',
  description TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT resources_resource_type_check
    CHECK (resource_type IN ('web', 'pdf', 'book', 'video', 'other'))
);

-- Documents keep the current backend compatible.
-- A document can belong to a resource, but manual ingestions can exist alone.
CREATE TABLE IF NOT EXISTS public.documents (
  id BIGSERIAL PRIMARY KEY,
  resource_id BIGINT REFERENCES public.resources(id) ON DELETE SET NULL,
  url TEXT NOT NULL,
  title TEXT,
  raw_content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Vectorized fragments used by the tutor chatbot/recommendation engine.
CREATE TABLE IF NOT EXISTS public.chunks (
  id BIGSERIAL PRIMARY KEY,
  document_id BIGINT NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  embedding VECTOR(768) NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  page_number INTEGER,
  section_title TEXT,
  token_count INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Student tasks/homework analyzed by the tutor.
CREATE TABLE IF NOT EXISTS public.assignments (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID,
  title TEXT,
  prompt TEXT NOT NULL,
  subject TEXT,
  grade_level TEXT,
  detected_topics TEXT[] NOT NULL DEFAULT '{}',
  difficulty TEXT,
  status TEXT NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT assignments_status_check
    CHECK (status IN ('new', 'analyzed', 'in_progress', 'completed', 'archived'))
);

-- Resource recommendations generated for one assignment.
CREATE TABLE IF NOT EXISTS public.assignment_recommendations (
  id BIGSERIAL PRIMARY KEY,
  assignment_id BIGINT NOT NULL REFERENCES public.assignments(id) ON DELETE CASCADE,
  resource_id BIGINT REFERENCES public.resources(id) ON DELETE SET NULL,
  chunk_id BIGINT REFERENCES public.chunks(id) ON DELETE SET NULL,
  reason TEXT,
  relevance_score DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Chat sessions for tutoring conversations.
CREATE TABLE IF NOT EXISTS public.chat_sessions (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID,
  assignment_id BIGINT REFERENCES public.assignments(id) ON DELETE SET NULL,
  title TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id BIGSERIAL PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chat_messages_role_check
    CHECK (role IN ('user', 'assistant', 'system'))
);

-- PDF or resource summaries generated by the app.
CREATE TABLE IF NOT EXISTS public.summaries (
  id BIGSERIAL PRIMARY KEY,
  resource_id BIGINT REFERENCES public.resources(id) ON DELETE SET NULL,
  document_id BIGINT REFERENCES public.documents(id) ON DELETE SET NULL,
  user_id UUID,
  summary_type TEXT NOT NULL DEFAULT 'general',
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT summaries_summary_type_check
    CHECK (summary_type IN ('general', 'short', 'detailed', 'study_guide'))
);

-- Exam-style practice generated from a task/resource/topic.
CREATE TABLE IF NOT EXISTS public.quizzes (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID,
  assignment_id BIGINT REFERENCES public.assignments(id) ON DELETE SET NULL,
  resource_id BIGINT REFERENCES public.resources(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  subject TEXT,
  topic TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.quiz_questions (
  id BIGSERIAL PRIMARY KEY,
  quiz_id BIGINT NOT NULL REFERENCES public.quizzes(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  question_type TEXT NOT NULL DEFAULT 'multiple_choice',
  options JSONB NOT NULL DEFAULT '[]'::jsonb,
  correct_answer TEXT,
  explanation TEXT,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT quiz_questions_question_type_check
    CHECK (question_type IN ('multiple_choice', 'open', 'true_false'))
);

CREATE INDEX IF NOT EXISTS documents_resource_id_idx
  ON public.documents (resource_id);

CREATE INDEX IF NOT EXISTS chunks_document_id_idx
  ON public.chunks (document_id);

CREATE INDEX IF NOT EXISTS chunks_embedding_cosine_idx
  ON public.chunks
  USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS resources_subject_idx
  ON public.resources (subject);

CREATE INDEX IF NOT EXISTS assignments_user_id_idx
  ON public.assignments (user_id);

CREATE INDEX IF NOT EXISTS chat_sessions_user_id_idx
  ON public.chat_sessions (user_id);

-- Search example used by the backend:
-- SELECT id, document_id, content, page_number, (embedding <=> '[...]'::vector) AS score
-- FROM public.chunks
-- ORDER BY score ASC
-- LIMIT 5;
-- migrations/2026_05_11_batch1.sql
--
-- Batch 1 de mejoras. Ejecutar en el SQL Editor de Supabase/Postgres.
-- El script es idempotente: se puede correr dos veces sin efectos adversos.


-- ─── 1) Deduplicar recursos con la misma URL ───────────────────────────────
-- Antes de crear el UNIQUE, nos quedamos con el resource mas antiguo por URL
-- y reasignamos sus documents a ese id, eliminando los duplicados.

-- Solo procesa filas con url no nula ni vacia (las ingestas manuales pueden
-- generar url sinteticas tipo "manual_ingestion_<timestamp>"; cada una es
-- unica, asi que no chocan).
WITH ranked AS (
  SELECT
    id,
    url,
    ROW_NUMBER() OVER (PARTITION BY url ORDER BY created_at ASC, id ASC) AS rn,
    FIRST_VALUE(id) OVER (PARTITION BY url ORDER BY created_at ASC, id ASC) AS keeper_id
  FROM public.resources
  WHERE url IS NOT NULL AND url <> ''
),
reassign AS (
  UPDATE public.documents d
  SET resource_id = r.keeper_id
  FROM ranked r
  WHERE d.resource_id = r.id
    AND r.rn > 1
  RETURNING d.id
)
DELETE FROM public.resources
WHERE id IN (SELECT id FROM ranked WHERE rn > 1);

-- ─── 2) UNIQUE en resources.url ────────────────────────────────────────────
-- Postgres permite multiples NULL en columnas UNIQUE por default,
-- asi que esto no afecta a ingestas manuales sin URL externa.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'resources_url_key'
      AND conrelid = 'public.resources'::regclass
  ) THEN
    ALTER TABLE public.resources
      ADD CONSTRAINT resources_url_key UNIQUE (url);
  END IF;
END $$;

-- ─── 3) ON DELETE CASCADE en documents.resource_id ─────────────────────────
-- Actualmente es SET NULL, lo que deja documentos huerfanos al borrar
-- un recurso. Con CASCADE, borrar un recurso borra sus documentos (y por
-- la FK de chunks a documents, tambien sus chunks).
ALTER TABLE public.documents
  DROP CONSTRAINT IF EXISTS documents_resource_id_fkey;

ALTER TABLE public.documents
  ADD CONSTRAINT documents_resource_id_fkey
  FOREIGN KEY (resource_id)
  REFERENCES public.resources(id)
  ON DELETE CASCADE;

-- ─── 4) Indice para borrado masivo en assignment_recommendations ──────────
CREATE INDEX IF NOT EXISTS assignment_recommendations_assignment_id_idx
  ON public.assignment_recommendations (assignment_id);

-- ─── 5) Indices utiles adicionales ─────────────────────────────────────────
CREATE INDEX IF NOT EXISTS resources_resource_type_idx
  ON public.resources (resource_type);

CREATE INDEX IF NOT EXISTS assignments_status_idx
  ON public.assignments (status);

CREATE INDEX IF NOT EXISTS chat_messages_session_id_idx
  ON public.chat_messages (session_id);

-- migrations/2026_05_11_users_tasks.sql
-- Crea las tablas users y tasks requeridas por el frontend (auth + calendario).
-- Ejecuta UNA VEZ en Supabase SQL Editor.


-- Extension pgcrypto para gen_random_uuid si aun no esta (Supabase normalmente la tiene)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ─── USERS ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS users_email_idx ON public.users (LOWER(email));

-- ─── TASKS ─────────────────────────────────────────────────────────────────
-- Tareas/agenda del usuario (distinto de "assignments" que es el analisis
-- pedagogico). Lo que aparece en el calendario del frontend.
CREATE TABLE IF NOT EXISTS public.tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  due_at TIMESTAMPTZ NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS tasks_user_id_idx ON public.tasks (user_id);
CREATE INDEX IF NOT EXISTS tasks_due_at_idx ON public.tasks (due_at);
CREATE INDEX IF NOT EXISTS tasks_user_pending_idx
  ON public.tasks (user_id, completed, due_at);


CREATE TABLE IF NOT EXISTS public.naatzo_users (
 id UUID PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL, password_hash TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS naatzo_users_email_lower_idx ON public.naatzo_users (LOWER(email));
INSERT INTO public.naatzo_users (id,name,email,password_hash)
VALUES ('11111111-1111-4111-8111-111111111111','Usuario de prueba','test@test.com','d749d862695f93d00e55a95287ec8659:2a27c938c8021948b4595ac9f4de4cedd9a7de8e3e682e89711de35e3be80bc9acc191a39005d8956406fb373e5469ccc049b7d3f1f5322525c59f1a28813a7d')
ON CONFLICT (LOWER(email)) DO NOTHING;
INSERT INTO public.users (id,name,email,password_hash)
SELECT id,name,email,'$2a$10$g3EE/AlicXyrY4rV7G2ZOePKphGw1Jr7Ogg.ynNfxrtHctLyU/DnC' FROM public.naatzo_users WHERE LOWER(email)='test@test.com'
ON CONFLICT (email) DO NOTHING;
COMMIT;
SELECT id, name, email FROM public.naatzo_users WHERE email='test@test.com';

