-- Hacka2026 tutor database example for Supabase/Postgres.
-- Run this in Supabase SQL Editor.

CREATE EXTENSION IF NOT EXISTS vector;

-- Public learning resources: PDFs, public pages, digital libraries, etc.
CREATE TABLE IF NOT EXISTS public.resources (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT,
  source_name TEXT,
  resource_type TEXT NOT NULL DEFAULT 'web',
  subject TEXT,
  grade_level TEXT,
  language TEXT NOT NULL DEFAULT 'es',
  description TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT resources_resource_type_check
    CHECK (resource_type IN ('web', 'pdf', 'book', 'video', 'other'))
);

-- Documents keep the current backend compatible.
-- A document can belong to a resource, but manual ingestions can exist alone.
CREATE TABLE IF NOT EXISTS public.documents (
  id BIGSERIAL PRIMARY KEY,
  resource_id BIGINT REFERENCES public.resources(id) ON DELETE SET NULL,
  url TEXT NOT NULL,
  title TEXT,
  raw_content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Vectorized fragments used by the tutor chatbot/recommendation engine.
CREATE TABLE IF NOT EXISTS public.chunks (
  id BIGSERIAL PRIMARY KEY,
  document_id BIGINT NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  embedding VECTOR(768) NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  page_number INTEGER,
  section_title TEXT,
  token_count INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Student tasks/homework analyzed by the tutor.
CREATE TABLE IF NOT EXISTS public.assignments (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID,
  title TEXT,
  prompt TEXT NOT NULL,
  subject TEXT,
  grade_level TEXT,
  detected_topics TEXT[] NOT NULL DEFAULT '{}',
  difficulty TEXT,
  status TEXT NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT assignments_status_check
    CHECK (status IN ('new', 'analyzed', 'in_progress', 'completed', 'archived'))
);

-- Resource recommendations generated for one assignment.
CREATE TABLE IF NOT EXISTS public.assignment_recommendations (
  id BIGSERIAL PRIMARY KEY,
  assignment_id BIGINT NOT NULL REFERENCES public.assignments(id) ON DELETE CASCADE,
  resource_id BIGINT REFERENCES public.resources(id) ON DELETE SET NULL,
  chunk_id BIGINT REFERENCES public.chunks(id) ON DELETE SET NULL,
  reason TEXT,
  relevance_score DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Chat sessions for tutoring conversations.
CREATE TABLE IF NOT EXISTS public.chat_sessions (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID,
  assignment_id BIGINT REFERENCES public.assignments(id) ON DELETE SET NULL,
  title TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id BIGSERIAL PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chat_messages_role_check
    CHECK (role IN ('user', 'assistant', 'system'))
);

-- PDF or resource summaries generated by the app.
CREATE TABLE IF NOT EXISTS public.summaries (
  id BIGSERIAL PRIMARY KEY,
  resource_id BIGINT REFERENCES public.resources(id) ON DELETE SET NULL,
  document_id BIGINT REFERENCES public.documents(id) ON DELETE SET NULL,
  user_id UUID,
  summary_type TEXT NOT NULL DEFAULT 'general',
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT summaries_summary_type_check
    CHECK (summary_type IN ('general', 'short', 'detailed', 'study_guide'))
);

-- Exam-style practice generated from a task/resource/topic.
CREATE TABLE IF NOT EXISTS public.quizzes (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID,
  assignment_id BIGINT REFERENCES public.assignments(id) ON DELETE SET NULL,
  resource_id BIGINT REFERENCES public.resources(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  subject TEXT,
  topic TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.quiz_questions (
  id BIGSERIAL PRIMARY KEY,
  quiz_id BIGINT NOT NULL REFERENCES public.quizzes(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  question_type TEXT NOT NULL DEFAULT 'multiple_choice',
  options JSONB NOT NULL DEFAULT '[]'::jsonb,
  correct_answer TEXT,
  explanation TEXT,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT quiz_questions_question_type_check
    CHECK (question_type IN ('multiple_choice', 'open', 'true_false'))
);

CREATE INDEX IF NOT EXISTS documents_resource_id_idx
  ON public.documents (resource_id);

CREATE INDEX IF NOT EXISTS chunks_document_id_idx
  ON public.chunks (document_id);

CREATE INDEX IF NOT EXISTS chunks_embedding_cosine_idx
  ON public.chunks
  USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS resources_subject_idx
  ON public.resources (subject);

CREATE INDEX IF NOT EXISTS assignments_user_id_idx
  ON public.assignments (user_id);

CREATE INDEX IF NOT EXISTS chat_sessions_user_id_idx
  ON public.chat_sessions (user_id);

-- Search example used by the backend:
-- SELECT id, document_id, content, page_number, (embedding <=> '[...]'::vector) AS score
-- FROM public.chunks
-- ORDER BY score ASC
-- LIMIT 5;
